name: Mirror repo to GitLab

on: [push, pull_request, delete]

jobs:
  call-nss-ops-mirror-workflow:
    uses: ITMO-NSS-team/NSS-Ops/.github/workflows/mirror-repo.yml@master
    with:
      GITLAB_URL: '<gitlab_repo_web_URL>'
    secrets:
      GITLAB_USER: ${{ secrets.GITLAB_USER }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
